from __future__ import annotations

from pathlib import Path

DOC_PATH = Path("docs/reviews/codex/FLEET_11TAB_MASTER_STATUS_20260303_203801.md")
EXPECTED_DOMAINS = {
    "dashboard",
    "upload",
    "emailpostfach",
    "messenger",
    "kalender",
    "aufgaben",
    "zeiterfassung",
    "projekte",
    "excel-docs-visualizer",
    "einstellungen",
    "floating-widget-chatbot",
}


def _read_doc() -> str:
    return DOC_PATH.read_text(encoding="utf-8")


def _extract_table_rows(text: str) -> list[list[str]]:
    rows: list[list[str]] = []
    in_table = False
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if line.startswith("| Domain | branch | dirty | diff(main...HEAD) | overlap | tests | status |"):
            in_table = True
            continue
        if in_table and line.startswith("|---"):
            continue
        if in_table and line.startswith("|"):
            cols = [c.strip() for c in line.strip("|").split("|")]
            if len(cols) == 7:
                rows.append(cols)
            continue
        if in_table and not line:
            break
    return rows


def _normalize_row(row: list[str]) -> dict[str, str]:
    return {
        "domain": row[0],
        "branch": row[1],
        "dirty": row[2],
        "diff": row[3],
        "overlap": row[4],
        "tests": row[5],
        "status": row[6],
    }


def test_fleet_status_doc_exists() -> None:
    assert DOC_PATH.exists(), f"Missing fleet status doc: {DOC_PATH}"


def test_fleet_status_doc_has_expected_header() -> None:
    text = _read_doc()
    assert "# FLEET 11TAB MASTER STATUS" in text
    assert "Generated by: Core Fleet Commander" in text


def test_fleet_status_table_has_exactly_11_rows() -> None:
    rows = _extract_table_rows(_read_doc())
    assert len(rows) == 11, f"Expected 11 domain rows, got {len(rows)}"


def test_fleet_status_contains_all_expected_domains() -> None:
    rows = _extract_table_rows(_read_doc())
    domains = {r[0] for r in rows}
    assert domains == EXPECTED_DOMAINS


def test_fleet_status_branch_prefix_is_codex() -> None:
    rows = _extract_table_rows(_read_doc())
    for row in rows:
        data = _normalize_row(row)
        assert data["branch"].startswith("codex/"), data


def test_fleet_status_dirty_is_zero_for_all_domains() -> None:
    rows = _extract_table_rows(_read_doc())
    for row in rows:
        data = _normalize_row(row)
        assert data["dirty"] == "0", data


def test_fleet_status_diff_is_zero_for_all_domains() -> None:
    rows = _extract_table_rows(_read_doc())
    for row in rows:
        data = _normalize_row(row)
        assert data["diff"] == "0", data


def test_fleet_status_overlap_is_ok_no_diff_for_all_domains() -> None:
    rows = _extract_table_rows(_read_doc())
    for row in rows:
        data = _normalize_row(row)
        assert data["overlap"] == "OK(no_diff)", data


def test_fleet_status_status_is_clean_for_all_domains() -> None:
    rows = _extract_table_rows(_read_doc())
    for row in rows:
        data = _normalize_row(row)
        assert data["status"] == "clean", data


def test_fleet_status_tests_column_is_na_placeholder() -> None:
    rows = _extract_table_rows(_read_doc())
    for row in rows:
        data = _normalize_row(row)
        assert data["tests"] == "n/a", data


def test_fleet_status_contains_automated_update_trail() -> None:
    text = _read_doc()
    assert "### Update at" in text
    assert "Overlap-Matrix regenerated:" in text


def test_fleet_status_references_overlap_matrix_artifacts() -> None:
    text = _read_doc()
    lines = [line.strip() for line in text.splitlines() if "OVERLAP_MATRIX_11_" in line]
    assert lines, "No overlap matrix references found"
    for line in lines:
        assert "docs/reviews/codex/OVERLAP_MATRIX_11_" in line
        assert ".md" in line


def test_fleet_status_doc_has_no_modified_markers_in_domain_table() -> None:
    rows = _extract_table_rows(_read_doc())
    for row in rows:
        data = _normalize_row(row)
        assert data["status"] != "modified", data
        assert data["overlap"] != "ERROR", data


def test_fleet_status_table_row_schema_is_stable() -> None:
    rows = _extract_table_rows(_read_doc())
    for row in rows:
        assert len(row) == 7
        assert row[0]
        assert row[1]
        assert row[2] in {"0", "1"}
        assert row[5] in {"n/a", "pass", "fail"}


def test_fleet_status_doc_contains_guidance_note() -> None:
    text = _read_doc()
    assert "Hinweis" in text
    assert "automatisiert" in text


def test_fleet_status_domain_names_are_unique() -> None:
    rows = _extract_table_rows(_read_doc())
    domains = [r[0] for r in rows]
    assert len(domains) == len(set(domains))


def test_fleet_status_includes_timestamp_section() -> None:
    text = _read_doc()
    assert "Timestamp:" in text


def test_fleet_status_doc_is_not_empty() -> None:
    text = _read_doc()
    assert len(text.splitlines()) >= 80


def test_fleet_status_domain_order_matches_expected_operational_sequence() -> None:
    rows = _extract_table_rows(_read_doc())
    ordered_domains = [r[0] for r in rows]
    expected_order = [
        "dashboard",
        "upload",
        "emailpostfach",
        "messenger",
        "kalender",
        "aufgaben",
        "zeiterfassung",
        "projekte",
        "excel-docs-visualizer",
        "einstellungen",
        "floating-widget-chatbot",
    ]
    assert ordered_domains == expected_order


def test_fleet_status_doc_uses_markdown_table_delimiter() -> None:
    text = _read_doc()
    assert "|---|---:" in text


def test_fleet_status_overlap_matrix_lines_have_absolute_workspace_prefix() -> None:
    text = _read_doc()
    lines = [line for line in text.splitlines() if "Overlap-Matrix regenerated:" in line]
    assert lines
    for line in lines:
        assert "/Users/gensuminguyen/Kukanilea/kukanilea_production/" in line


def test_fleet_status_doc_keeps_codex_review_location() -> None:
    text = _read_doc()
    assert "docs/reviews/codex" in text


def test_fleet_status_doc_has_generated_by_block_near_top() -> None:
    lines = _read_doc().splitlines()
    head = "\n".join(lines[:12])
    assert "Generated by: Core Fleet Commander" in head
