from __future__ import annotations

import logging
import os
from pathlib import Path

import requests

logger = logging.getLogger("kukanilea.ai.diagnostics")

OLLAMA_HOST = os.environ.get("OLLAMA_HOST", "http://localhost:11434")
DIAGNOSTIC_MODEL = "llama3"

class DiagnosticAgent:
    """
    Read-Only AI Diagnostic Agent for KUKANILEA.
    SOURCE: https://ai-act-service-desk.ec.europa.eu/en/ai-act/article-50 (Art. 50 Transparency)
    """

    def __init__(self, model=DIAGNOSTIC_MODEL):
        self.model = model

    def analyze_error(self, log_snippet: str) -> str:
        enabled = os.environ.get("KUK_DIAG_ENABLED", "0") == "1"
        if not enabled:
            return "AI Diagnostics disabled (KUK_DIAG_ENABLED=0)."

        prompt = f"""You are a senior software engineer. Analyze this error trace and provide a unified diff to fix it.
CONSTRAINTS: Read-Only analysis. NO code mutation allowed. NO raw filesystem writes other than the diagnosis file.

ERROR LOGS:
{log_snippet}

Provide the diagnosis in the following format:
# AI Diagnosis (KUKANILEA)
## Root Cause Hypothesis
## Repro Steps
## Proposed Fix (unified diff)
## Tests to run
## Risk Notes
## AI Transparency Notice (AI Act Art. 50)
This diagnosis was generated by a local AI system and requires human review.
"""

        try:
            response = requests.post(
                f"{OLLAMA_HOST}/api/generate",
                json={"model": self.model, "prompt": prompt, "stream": False},
                timeout=30,
            )
            response.raise_for_status()
            analysis = response.json().get("response", "No diagnosis received.")
            
            output_dir = Path("evidence/diagnostics")
            output_dir.mkdir(parents=True, exist_ok=True)
            diag_file = output_dir / "DIAGNOSIS.md"
            diag_file.write_text(analysis)
            
            return analysis

        except Exception as e:
            logger.error(f"AI Diagnostics failed: {e}")
            return f"AI Diagnostics failed: {str(e)}"
