import argparse
import os
from pathlib import Path

import requests


def redact_secrets(text):
    # Very basic redaction placeholder
    return text.replace("KUKANILEA_SECRET", "REDACTED")

def diagnose(log_path, output_dir):
    enabled = os.environ.get("KUK_DIAG_ENABLED", "0") == "1"
    if not enabled:
        print("AI Diagnostics disabled (KUK_DIAG_ENABLED=0)")
        return

    log_path = Path(log_path)
    if not log_path.exists():
        print(f"Log file {log_path} not found.")
        return

    logs = log_path.read_text()
    logs = redact_secrets(logs[:10000]) # Limit input size

    prompt = f"""You are a senior software engineer. Analyze these logs and provide a diagnosis.
LOGS:
{logs}

Provide the diagnosis in the following format:
# AI Diagnosis (KUKANILEA)
## Root Cause Hypothesis
## Repro Steps
## Proposed Fix (unified diff)
## Tests to run
## Risk Notes
## AI Transparency Notice (AI Act Art. 50)
This diagnosis was generated by a local AI model.
"""

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    diag_path = output_dir / "DIAGNOSIS.md"

    # Call local Ollama if available
    try:
        response = requests.post("http://localhost:11434/api/generate", json={
            "model": "llama3",
            "prompt": prompt,
            "stream": False
        }, timeout=30)
        
        if response.status_code == 200:
            diagnosis_text = response.json().get("response", "No diagnosis received.")
            diag_path.write_text(diagnosis_text)
            print(f"Diagnosis written to {diag_path}")
        else:
            print(f"Ollama error: {response.status_code}")
    except Exception as e:
        print(f"Could not connect to local LLM: {str(e)}")
        # Fallback to a mock diagnosis for demonstration if needed, 
        # but the task implies it should actually try to call the LLM.

def main():
    parser = argparse.ArgumentParser(description="AI Diagnostic tool (READ-ONLY)")
    parser.add_argument("--logs", required=True, help="Path to logs/pytest output")
    parser.add_argument("--out", default="evidence/diagnostics", help="Output directory")
    args = parser.parse_args()
    
    diagnose(args.logs, args.out)

if __name__ == "__main__":
    main()
